application:
  name: KTB_7WEEK
  auth:
    secret: secretKey
    token:
      expire: 10

springdoc:
  api-docs:
    path: /api-docs # API ?? ?? (???: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui.html # Swagger UI ??
  info:
    title: My API Specification
    version: v1.0.0
    description: This document descript my project how to use

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KTB_7WEEK?serverTimezone=UTC&useSSL=false
    username: root
    password: Hss@857942
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: none   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug